### PR TITLE
Fix readme and gem auto-loading

### PR DESCRIPTION
**Pull request by okoriko**
I fixed some typos in the readme.
Also now the gem loads properly e.g. in rails as it was looking for the `lib/kuromoji-ruby.rb` (to match the gem name).

### CODE REVIEW

**Comment by toyama0919** [comment]
Thanks！

**Comment by okoriko** [comment]
@toyama0919 ありがとうございます！
RubyGemsにリリーズをするのは可能でしょうか？

**Comment by toyama0919** [comment]
released.

kuromoji-ruby | RubyGems.org | your community gem host https://rubygems.org/gems/kuromoji-ruby/versions/0.0.4

**Comment by okoriko** [comment]
thank you!

**Pull request merged**
